### ISSUE TITLE
Fail to upload file

### ISSUE THREAD

**Issue by perqin** [zhengqi-big-god-take-me-fly/Tumoji-Server#2]
1. The server will not create `storage/image` directory automatically when it doesn't exist.
2. After directory created manually and upload the file I get such error and the server is down:
```
/home/perqin/Workspaces/Tumoji/Tumoji-Server/common/models/image.js:42
        var fileInfo = fileObj.files.file[0];
                                         ^
TypeError: Cannot read property '0' of undefined
    at /home/perqin/Workspaces/Tumoji/Tumoji-Server/common/models/image.js:42:42
    at /home/perqin/Workspaces/Tumoji/Tumoji-Server/node_modules/loopback-component-storage/lib/storage-handler.js:203:5
    at IncomingForm.<anonymous> (/home/perqin/Workspaces/Tumoji/Tumoji-Server/node_modules/formidable/lib/incoming_form.js:105:9)
    at emitNone (events.js:86:13)
    at IncomingForm.emit (events.js:185:7)
    at IncomingForm._maybeEnd (/home/perqin/Workspaces/Tumoji/Tumoji-Server/node_modules/formidable/lib/incoming_form.js:553:8)
    at endFunc (/home/perqin/Workspaces/Tumoji/Tumoji-Server/node_modules/loopback-component-storage/lib/storage-handler.js:157:12)
    at WriteStream.<anonymous> (/home/perqin/Workspaces/Tumoji/Tumoji-Server/node_modules/loopback-component-storage/lib/storage-handler.js:161:7)
    at emitNone (events.js:86:13)
    at WriteStream.emit (events.js:185:7)
    at WriteStream.<anonymous> (/home/perqin/Workspaces/Tumoji/Tumoji-Server/node_modules/loopback-component-storage/lib/providers/filesystem/index.js:185:14)
    at emitNone (events.js:91:20)
    at WriteStream.emit (events.js:185:7)
    at finishMaybe (_stream_writable.js:515:14)
    at afterWrite (_stream_writable.js:389:3)
    at onwrite (_stream_writable.js:379:7)

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! Tumoji-Server@1.0.0 start: `node .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Tumoji-Server@1.0.0 start script 'node .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Tumoji-Server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Tumoji-Server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Tumoji-Server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/perqin/Workspaces/Tumoji/Tumoji-Server/npm-debug.log
```
By the way, what is the right key for form-data? I currently use such POST data with Postman:
```
var data = new FormData();
data.append("perqin.png", "default_avatar.png");

var xhr = new XMLHttpRequest();
xhr.withCredentials = true;

xhr.addEventListener("readystatechange", function () {
  if (this.readyState === 4) {
    console.log(this.responseText);
  }
});

xhr.open("POST", "http://127.0.0.1:3000/api/images?access_token=u74gCy125kGlQRVBUdbmMkbIJFWLTdBzqIG5XhmhRvmsmuTMgK1gegM75qZodmKh");
xhr.setRequestHeader("cache-control", "no-cache");
xhr.setRequestHeader("postman-token", "b04cd8eb-ddb7-7097-c44d-1d67f3360f91");

xhr.send(data);
```

**Comment by perqin** [comment]
Should use the following HTTP request:
 * Method: POST
 * Query: access_token=[access_token]
 * Body: form-data file with key `file`
